server:
  port: 9080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: address-migrator
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
        discovery:
          server-discovery-name: spring-batch-lightmin-server
      batch:
        #default jdbc
        repository-type: jdbc
        #default dataSource
        data-source-name: dataSource
        #default BATCH_
        table-prefix: BATCH_
      repository:
        remote:
          server-discovery-name: spring-batch-lightmin-server
          discover-remote-repository: true
eureka:
  instance:
    hostname: 'localhost'